server.port: 8083
spring:
  kafka:
    listener:
      ack-mode: record
    bootstrap-servers: localhost:9092 #77.50.236.215:48995 #${SPRING_KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: mock